# Generated by Django 3.2.8 on 2021-10-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
