# Generated by Django 3.2.8 on 2021-10-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
