# Generated by Django 3.2.8 on 2021-10-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0004_auto_20211022_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
    ]
