# Generated by Django 3.2.8 on 2021-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0005_remove_about_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
