# Generated by Django 3.2.8 on 2021-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0006_alter_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
