# Generated by Django 3.2.8 on 2021-10-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgershop', '0007_auto_20211022_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='title',
            new_name='name',
        ),
    ]
